replicaCount: 1

image:
  repository: acrdungnpv.azurecr.io/be
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: NodePort
  port: 5000
  nodePort: 30500

env:
  PORT: "5000"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST: "db-postgresql.db.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "db"
