replicaCount: 1

image:
  repository: be
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

env:
  PORT: "5000"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "version_db"
