replicaCount: 1

image:
  repository: be
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000
  nodePort: 30500

env:
  PORT: "5000"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST: "db-postgresql"
  DB_PORT: "5432"
  DB_NAME: "db"
