apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "be.fullname" . }}
  labels:
    app: {{ include "be.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "be.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "be.name" . }}
    spec:
      containers:
        - name: {{ include "be.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.env.PORT | int }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"
